### ISSUE TITLE
Is it possible using e2immu jar in my JDK8 environment?

### ISSUE THREAD

**Issue by zhizhixiongxuwei** [e2immu/e2immu#51]
I use eclipse jdt (out of eclipse osgi mode) in the past, however i find this project have some analyzer feature which I needed.
I am not sure is it fine for me to use it with JDK8. It seems to build in JDK16?

**Comment by bnaudts** [comment]
The e2immu/e2immu-support jar has been compiled with JDK 10, but can easily compile with JDK 8 by removing one or two methods. 

The analyzer e2immu/e2immu cannot easily be compiled with JDK 8. It uses the JDK 16 language features (records, instance of patterns) throughout the code, and many JDK calls (such as toList() on Stream) that are much more recent than JDK 8.

**Comment by zhizhixiongxuwei** [comment]
Thanks for your reply. As you said, the analyzer e2immu/e2immu uses the JDK16 features, so if I update to JDK11 (LTS) it will also work inproperly？

**Comment by bnaudts** [comment]
Indeed, the JDK/JRE 11 runtime system will complain that it sees byte code which is newer than it can handle.
